name: CI
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - "3.0.1"

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v2.0

      - name: Build and test
        shell: bash
        run: sbt ++${{ matrix.scala }} test
